matryoshka:
  outputs:
    prod:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('DBT_SCHEMA_PROD') }}"
      threads: 4
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('DBT_SCHEMA_DEV') }}"
      threads: 2
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
  target: dev
